language: perl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y librdf-perl
install:
  - "cpanm --quiet --installdeps --notest RDF::Trine"
  - "cpanm --quiet --installdeps --notest RDF::Query"
  - "cpanm --quiet --notest Module::Install::AuthorTests"
  - "cpanm --quiet --notest Module::Install::DOAPChangeSets"
  - "cpanm --quiet --notest IRI"
  - "cpanm --quiet --notest namespace::clean"
  - "cpanm --quiet --notest Data::UUID"
  - "cpanm --quiet --notest DateTime::Format::W3CDTF"
  - "cpanm --quiet --notest I18N::LangTags"
  - "cpanm --quiet --notest URI::Namespace"
  - "cpanm --quiet --notest URI::Escape"
  - "cpanm --quiet --notest DBD::Pg"
  - "cpanm --quiet --notest Moo"
  - "cpanm --quiet --notest MooX::Log::Any"
  - "cpanm --quiet --notest Test::Modern"
  - "cpanm --quiet --notest Test::Roo"
  - "cpanm --quiet --notest Test::LWP::UserAgent"
  - "cpanm --quiet --notest Type::Tiny"
  - "cpanm --quiet --notest HTTP::Negotiate"
  - "cpanm --quiet --notest Math::Cartesian::Product"
env:
  - RDFTRINE_STORE_PG_DATABASE="travis_ci_test" RDFTRINE_STORE_PG_MODEL="testmodel"
script:
  - "perl Makefile.PL && make test"
